_target_: pipelines.pipeline_utils.PipelineConfigs

pretrained_model_name_or_path: "Qwen/Qwen-Image-Edit-2511"
handler_name: pipelines.pipeline_qwenimage_edit_plus.QwenImageEditPlusForwardHandler
tune_modules: [""]
load_modules: ["scheduler", "processor", "tokenizer", "vae", "transformer", "text_encoder"]