defaults:

  - pipeline: qwenimage_edit_plus
  - adapter: lora
  - loss: flow_matching

  - dataset@tune_set: tune_set
  - dataset@eval_set: eval_set
  - dataset@data_module: data_module

  - _self_


# Runtime
project_name: pipeline_finetune
timestamp: ${now:%Y%m%d-%H%M%S}
output_dir: outputs/${project_name}/${timestamp}
logging_dir: ${output_dir}/logs
save_dir: ${output_dir}/checkpoints


# Accelerator
accelerator:
  mixed_precision: bf16
  gradient_accumulation_steps: 1
  log_with: tensorboard


# Tuning
tune:
  random_seed: 42
  max_grad_norm: 1.0
  max_tuning_steps: 1000
  save_steps: 100
  eval_steps: 100
  save_dir: ${save_dir}
  

# Hydra
hydra:
  run:
    dir: ${output_dir}/hydra-configs